server:
  port: 8001
  servlet:
    context-path: /member

spring:
  datasource:
    url: jdbc:mysql://140.210.221.183:3307/train_member?characterEncoding=UTF8&useSSL=false
    username: root
    password: ccsdsg2016
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: member
  data:
    redis:
      host: 140.210.221.183
      port: 6379
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: train_cache_
      time-to-live: 60s


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com:
      example:
        mapper: trace
