GET http://localhost:8002/business/admin/confirm-order/query-list?page=1&size=10
Accept: application/json

###

GET http://localhost:8000/business/train/query-all
Accept: application/json

###

GET http://47.101.44.52/business/hello
Accept: application/json

###
