server:
  port: 8002
  servlet:
    context-path: /business

spring:
  datasource:
    url: jdbc:mysql://140.210.221.183:3307/train_business?characterEncoding=UTF8&useSSL=false
    username: root
    password: ccsdsg2016
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: business
  data:
    redis:
      host: 140.210.221.183
      port: 6379
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: train_cache_
      time-to-live: 60s
  cloud:
    sentinel:
      transport:
        dashboard: 140.210.221.183:8858
        port: 8719

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com:
      example:
        mapper: trace
#rocketmq:
#  name-server: http://localhost:9876
#  producer:
#    group: default
#

