server:
  port: 8003
  servlet:
    context-path: /batch

spring:
  datasource:
    url: jdbc:mysql://140.210.221.183:3307/train_batch?characterEncoding=UTF8&useSSL=false
    username: root
    password: ccsdsg2016
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: batch
  cloud:
    sentinel:
      transport:
        dashboard: 140.210.221.183:8858
        port: 8719
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com:
      example:
        mapper: trace
